server:
    port: 8777
    ssl:
        key-store: keystore.p12
        key-store-password: password
        keyStoreType: PKCS12
        keyAlias: tomcat
        
# keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650